run:
  timeout: 5m
  allow-parallel-runners: true

issues:
  exclude-rules:
    - path: "_test.go"
      linters:
        - lll

linters:
  enable:
    #### default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    #### non-default
    - dupl
    - ginkgolinter
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - govet
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - typecheck
    - unconvert
    - unparam
